import localFont from "next/font/local";
import "./globals.css";
import Header from "./dashboard/_components/Header";
import { ApiProvider } from "./_context/APIDetailContext";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApiProvider>
          <div>
            <Header />
            <Toaster />
            <div>
              {children}
            </div>
          </div>
        </ApiProvider>
      </body>
    </html>
  );
}
